### ISSUE TITLE
Provide a practical example to use this utility

### ISSUE THREAD

**Issue by Thireus** [peercoin/FindstakeJS#1]
Would it be possible to provide documentation and a practical example? By that I mean explain to a lambda user how to fill the fields for him to launch the calculation process for his own transaction.

There are several fields like BlockFromTime, StakeModifier, PrevTxOffset for which I'm not sure everyone knows where to get the data from.

A practical example with an existing and old transaction that already staked would be of a great help. :)

**Comment by jointhepartypooper** [comment]
i am working on phase 2, which would only ask for a Tx Id everyone could lookup in peerunity.so reduced to 1 input and a go button, just like google!
I just send a question to snakie if he could provide that data so lets be patient.

Date: Wed, 21 Jan 2015 13:56:29 -0800

**Comment by Thireus** [comment]
Awesome thank you! I've seen on the forum that you've posted usable data :).

http://www.peercointalk.org/index.php?topic=3506.msg36900#msg36900

Thank you for your work!
