### ISSUE TITLE
Page needs to be refreshed in order to start a new FindStake

### ISSUE THREAD

**Issue by Thireus** [peercoin/FindstakeJS#4]
There is no visible button after the FindStake process is complete, which means it is not possible to start a new FindStake process again. The page has to be refreshed to start a new find.

Thank you for fixing the other issues (you can close them when fixed). You are doing an amazing work!

(verified on findstake_singlepage.html)

**Comment by jointhepartypooper** [comment]
yes, either click on find stake link at the top or F5 to start over. Not a real big issue.
Date: Fri, 6 Feb 2015 20:05:44 -0800

**Comment by Thireus** [comment]
There is no problem for me jointhepartypooper :). I was just pointing out the issue so you can eventually make it more user-friendly for other users.

Thanks for your work!

**Comment by jointhepartypooper** [comment]
implemented vue, should solve the issue
