### ISSUE TITLE
No error reported to the user on "Retrieving Data..." failure (i.e. 404 Not Found)

### ISSUE THREAD

**Issue by Thireus** [peercoin/FindstakeJS#5]
I'm trying to FindStake with my PPC address: "PThireusGvcB3npn7Zf2LrRtEV2FFkvUMj", but the tool stays stuck on "Retrieving Data..." without warning me that the download failed because of Error 404 (data not found for my address).
- Would it be possible to inform me whenever the data failed to be retrieved instead on staying stuck on "Retrieving Data..."?
- Why is my address (and certainly several others) not part of the pre-generated data?

**Comment by jointhepartypooper** [comment]
added an ajax fail callback. But in your case I think it is not correctly installed as my localhost has no problem finding outputs on PThireusGvcB3npn7Zf2LrRtEV2FFkvUMj
