### ISSUE TITLE
Weird error when npm installing FindstakeJS

### ISSUE THREAD

**Issue by ondrejsojka** [peercoin/FindstakeJS#6]
I'm trying to install FindstakeJS to - wait for it - find my stake. Under linux, I'm getting these weird errors (on the tail - including all stdout from that npm install except http downloading  before leveldown). Any help appreciated.

> leveldown@0.10.4 install /home/onda/findstake/node_modules/level/node_modules/leveldown
> node-gyp rebuild

npm http 200 https://registry.npmjs.org/prr
npm http 200 https://registry.npmjs.org/errno/-/errno-0.1.1.tgz
npm http GET https://registry.npmjs.org/prr/-/prr-0.0.0.tgz
npm http 200 https://registry.npmjs.org/bl/-/bl-0.8.2.tgz
npm http 200 https://registry.npmjs.org/semver/-/semver-2.3.2.tgz
npm http 200 https://registry.npmjs.org/xtend/-/xtend-3.0.0.tgz
npm http 200 https://registry.npmjs.org/prr/-/prr-0.0.0.tgz
npm http 200 https://registry.npmjs.org/deferred-leveldown
npm http GET https://registry.npmjs.org/deferred-leveldown/-/deferred-leveldown-0.2.0.tgz
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/onda/findstake/node_modules/level/node_modules/leveldown
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm http 200 https://registry.npmjs.org/deferred-leveldown/-/deferred-leveldown-0.2.0.tgz
npm ERR! weird error 1
npm ERR! Error: ENOENT, open '/home/onda/tmp/npm-8424-iSXrA1RK/1425327221185-0.5663438767660409/package/foot.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-44-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/onda/findstake
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/onda/tmp/npm-8424-iSXrA1RK/1425327221185-0.5663438767660409/package/foot.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/onda/findstake/npm-debug.log
npm ERR! not ok code 0

**Comment by jointhepartypooper** [comment]
this is more a leveldown issue i know nothing of. Pls ask on that github?. That said, I think I'll replace level with pouchdb-server given the installation issues of level down. Meanwhile, you can use the FindstakeSinglePage or simply goto http://findstakejs.peercointalk.org/

**Comment by jointhepartypooper** [comment]
Prebuilt binaries:
LevelDOWN uses node-pre-gyp to support prebuilt binaries. For a list of supported prebuilt platform binaries see https://github.com/Level/leveldown/releases
